---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian8
    image: turgon37/docker-debian8-ansible
  - name: debian9
    image: turgon37/docker-debian9-ansible
  - name: debian10
    image: turgon37/docker-debian10-ansible
  - name: centos7
    image: turgon37/docker-centos7-ansible
lint: yamllint .
provisioner:
  name: ansible
  options:
    diff: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
